time_step = 40
is_training = True
batch_size = 700
rec_file = '/home/daiab/machine_disk/code/Stock-Predict-RNN/v5/data/_.tfrecords'
cells_per_rnn_layer = 200
hidden_layers = 10
rnn_keep_prop = 1.0
num_samples = 1e7
epochs = 20
iter_num = int(num_samples / batch_size * 20) # 500000
learning_rate = 0.001
momentum = 0.9
power = 0.6
decay_steps = iter_num
ckpt_file = None
